In [1]:
import datetime
import numpy as np
import pandas as pd

import plotly.graph_objects as go
from ipywidgets import widgets

In [13]:
city_df = pd.read_csv("c:\\Resources\\Project\\10_City_update.csv")
weather_df = pd.read_csv("c:\\Resources\\Project\\AllDf2.csv")
group_df =  pd.merge(city_df,weather_df, on=("CityName","Year"), suffixes=("_Medical","_Weather"))
group_df['City'] = group_df['CityName'].astype(str)
group_df['Year'] = group_df['Year'].astype(str)
group_df["Temperature"] = group_df['Temperature'].astype(str)
group_df["Snow"] = group_df['Snow 24h'].astype(str)
group_df["Cloudiness"] = group_df['Clouds All'].astype(str)
group_df["Population"] = group_df['PopulationCount'].astype(str)
group_df.head()

,Year,StateAbbr,StateDesc,CityName,GeographicLevel,Category,UniqueID,Measure,Data_Value_Unit,DataValueTypeID,...,GeoLocation,MeasureId,Short_Question_Text,Temperature,Snow 24h,Clouds All,City,Snow,Cloudiness,Population
0,2017,PA,Pennsylvania,Philadelphia,City,Unhealthy Behaviors,4260000,Binge drinking among adults aged >=18 Years,%,AgeAdjPrv,...,"(40.0093147808, -75.1333888571)",BINGE,Binge Drinking,55.62353229,63.84,60.037795,Philadelphia,63.84,60.03779545,1526006
1,2017,PA,Pennsylvania,Philadelphia,City,Health Outcomes,4260000,Mental health not good for >=14 days among adu...,%,AgeAdjPrv,...,"(40.0093147808, -75.1333888571)",MHLTH,Mental Health,55.62353229,63.84,60.037795,Philadelphia,63.84,60.03779545,1526006
2,2017,PA,Pennsylvania,Philadelphia,City,Unhealthy Behaviors,4260000,Obesity among adults aged >=18 Years,%,AgeAdjPrv,...,"(40.0093147808, -75.1333888571)",OBESITY,Obesity,55.62353229,63.84,60.037795,Philadelphia,63.84,60.03779545,1526006
3,2016,PA,Pennsylvania,Philadelphia,City,Unhealthy Behaviors,4260000,Sleeping less than 7 hours among adults aged >...,%,AgeAdjPrv,...,"(40.0093147808, -75.1333888571)",SLEEP,Sleep <7 hours,55.85759811,83.89,56.779268,Philadelphia,83.89,56.77926789,1526006
4,2017,NY,New York,New York,City,Health Outcomes,3651000,Mental health not good for >=14 days among adu...,%,AgeAdjPrv,...,"(40.694960689, -73.9313850409)",MHLTH,Mental Health,56.192299600000005,85.02,40.148791,New York,85.02,40.14879086,8175133

In [18]:
# Create dropdowns.

city = widgets.Dropdown(
    description='City:   ',
    #value='1',
    options=group_df['City'].astype(str).unique().tolist()
)
year = widgets.Dropdown(
    description='Year:   ',
    value='2016',
    options=group_df['Year'].astype(str).unique().tolist()
)

In [23]:
clouds = widgets.Dropdown(
    description='Cloudiness:   ',
    #value='1',
    options=group_df['Clouds All'].astype(str).unique().tolist()
)

In [24]:
# Assign an empty figure widget with two traces
trace1 = go.Bar(name='City Temp', x=group_df['CityName'], y=group_df['Temperature'])
g = go.FigureWidget(data=[trace1],
                    layout=go.Layout(
                        title=dict(
                            text='City Temp'
                        )
                    ))

In [27]:
def validate():
    if city.value in city_df['City'].unique() and year.value in city_df['Year'].unique():
        return True
    else:
        return False


def response(change):
    if validate():
        filter_list = [i and j for i, j in
                       zip(city_dff['City'] == city.value, city_df['Year'] == year.value)]
        temp_df = group_df[filter_list]
        x1 = group_df['City']
        y1 = group_df['Temperature']
        with g.batch_update():
            g.data[0].x = x1
            g.data[0].y = y1
            g.layout.xaxis.title = 'City'
            g.layout.yaxis.title = 'Temp'


city.observe(response, names="value")
year.observe(response, names="value")

In [28]:
container = widgets.HBox([city, year])
widgets.VBox([container])

VBox(children=(HBox(children=(Dropdown(description='City:   ', options=('Philadelphia', 'New York', 'Chicago',â€¦

In [ ]:
g